//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.Binhluans = new HashSet<Binhluan>();
        }
    
        public int MaBaiViet { get; set; }
        public string NoiDung { get; set; }
        public string AnhChuDe { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaDinhDuong { get; set; }
        public Nullable<int> MaTinTuc { get; set; }
        public Nullable<int> MaKienThuc { get; set; }
        public string TenChuDe { get; set; }
        public string TieuDe { get; set; }
        public Nullable<int> MaAdmin { get; set; }
        public string HuongDan { get; set; }
        public Nullable<int> MaBaiVietKT { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual BaiVietKT BaiVietKT { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual DinhDuong DinhDuong { get; set; }
        public virtual KT KT { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual TinTuc TinTuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Binhluan> Binhluans { get; set; }
    }
}
